apiVersion: v1
kind: Namespace
metadata:
  name: "{{name}}"
  labels:
    istio-injection: enabled
    modelmesh-enabled: "true"
    katib.kubeflow.org/metrics-collector-injection: enabled
    serving.kubeflow.org/inferenceservice: enabled
