apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "mlpipelines-manager"
  namespace: "{{name}}"
rules:
- apiGroups:
  - argoproj.io
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - deletecollection
  - patch
  - update
