apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "kserve-manager"
  namespace: "{{name}}"
rules:
- apiGroups:
  - serving.kubeflow.org
  - serving.kserve.io
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups: [serving.knative.dev]
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - deletecollection
  - patch
  - update
