parameters:
- name: kubernetes.context
  fromEnv: HUB_KUBECONTEXT
  default: rancher-desktop
- name: dns.domain
  value: localhost
- name: storage.class
  fromEnv: STORAGE_CLASS
- name: ingress.protocol
  value: http
- name: dex.authproxy.cookieExpire
  value: "'24h0m0s'"
- name: dex.passwordDb.email
  brief: Kubeflow admin user name
  fromEnv: USER
  default: admin@kubeflow.local
- name: dex.passwordDb.password
  brief: Kubeflow admin user password
  fromEnv: DEX_PASSWORD
