parameters:
- name: ingress
  parameters:
  - name: protocol
    value: http
  - name: hosts
    value: kubeflow.${dns.domain}
  - name: hosts
    component: istio-ingressgateway
    value: kubeflow.${dns.domain}
  - name: hosts
    component: argo
    value: "argo.${dns.domain}"
  - name: hosts
    component: minio
    value: minio.${dns.domain}
  - name: hosts
    component: dex
    value: auth.${dns.domain}

- name: istio
  parameters:
  - name: namespace
    value: istio-system
  - name: version
    value: 1.15.1
  - name: ingressGateway
    value: istio-ingressgateway
