parameters:
- name: kubernetes.context
  fromEnv: HUB_KUBECONTEXT
  default: rancher-desktop
- name: dns.domain
  value: localhost
- name: storage.class
  brief: |
    Name of the existing Kubernetes storage class.
    This class will be used to provision PVs for Kubeflow such and notebooks and databases

    To check for available storage classes run: `kubectl get sc`
  fromEnv: STORAGE_CLASS

- name: dex
  parameters:
  - name: namespace
    value: kube-ingress
  - name: passwordDb.email
    brief: Kubeflow admin user name
    fromEnv: USER
    default: admin@kubeflow.local
  - name: passwordDb.password
    brief: Kubeflow admin user password
    fromEnv: DEX_PASSWORD
