apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "image-classifier"
spec:
  predictor:
    model:
      modelFormat:
        name: pytorch
      storageUri: "gs://kfserving-examples/models/torchserve/image_classifier/v1"
      
      