apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "image-classifier"
spec:
  predictor:
    minReplicas: 0
    maxReplicas: 10
    scaleTarget: 1
    scaleMetric: rps
    model:
      modelFormat:
        name: pytorch
      storageUri: "gs://kfserving-examples/models/torchserve/image_classifier/v1"
      
      
