apiVersion: skaffold/v3
kind: Config
# metadata:
#   name: app-
build:
  artifacts:
  - image: ghcr.io/epam/hub-kubeflow-stacks/replikate
    hooks:
      after:
      - command: ["bin/set-image"]
        # os: [darwin, linux]
    sync:
      manual:
      - src: "src/*.py"
        dest: /app
        strip: src/
  tagPolicy:
    dateTime:
      format: 20060102-150405
manifests:
  kustomize:
    paths: ["kustomize/skaffold"]
profiles:
- activation:
  - env: KUBECONFIG=!
  build:
    local:
      useBuildkit: false
      useDockerCLI: true
  name: local
- build:
    cluster:
      dockerConfig:
        path: k8s/dockerconfig.json
        secretName: replikate-docker
  name: kaniko
portForward:
- resourceType: Deployment
  resourceName: replikate
  port: 9229
  localPort: 9229
