apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: kube-ingress
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: calm-massie-154-external-dns
  namespace: kube-ingress
  annotations:
    cnrm.cloud.google.com/project-id: "or2-msq-epm-daso-t1iylu"
spec:
  displayName: external-dns
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: calm-massie-154-external-dns
  namespace: kube-ingress
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: calm-massie-154-external-dns
  bindings:
  - role: roles/iam.workloadIdentityUser
    members:
    - serviceAccount:or2-msq-epm-daso-t1iylu.svc.id.goog[kube-ingress/external-dns]
  - role: roles/dns.admin
    members:
    - serviceAccount:or2-msq-epm-daso-t1iylu.svc.id.goog[kube-ingress/external-dns]
