parameters:
- name: dns.name
  fromEnv: HUB_STACK_NAME
- name: dns.domain
  fromEnv: HUB_DOMAIN_NAME  

- name: azure
  parameters:
  - name: location
    fromEnv: AZURE_REGION
  - name: resourceGroupName
    fromEnv: AZURE_RESOURCE_GROUP_NAME
  - name: clientId
    brief: |
      Client ID of Azure Service Principal with DNS Contributor role
      How to create Service Principals: 
      https://learn.microsoft.com/en-us/azure/purview/create-service-principal-azure
    fromEnv: DNS_CONTRIBUTOR_SP_CLIENT_ID
  - name: clientSecret
    brief: |
      Client Secret of the Azure Service Principal with DNS Contributor role
      How add a Client Secret to the Service Principal
      https://learn.microsoft.com/en-us/azure/purview/create-service-principal-azure#adding-a-secret-to-the-client-credentials
    fromEnv: DNS_CONTRIBUTOR_SP_SECRET

- name: kubernetes
  component: aks
  parameters:
  - name: cluster.name
    fromEnv: KUBERNETES_NAME
    brief: |
      AKS Cluster name
    default: superhub
  - name: cluster.version
    brief: |
      Kubernetes version
      Please check https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli
      which versions are supported
    value: "1.25"
  - name: node.machineType
    brief: |
      Size of Kubernetes node
      See https://learn.microsoft.com/en-us/azure/virtual-machines/sizes what
      sizes are available
    default: "Standard_B2s"
    fromEnv: KUBERNETES_MACHINE_TYPE
  - name: node.count
    default: 2
    fromEnv: KUBERNETES_NODE_COUNT

- name: nginx
  parameters:
  - name: loadBalancerSourceRanges
    brief: |
      IP ranges from where public Nginx LoadBalancer should be accessible
      The field supports space-separated list of values
    fromEnv: WHITELISTED_CIDR

