parameters:
  - name: projectId
    fromEnv: GOOGLE_PROJECT
  - name: stateBucketName
    fromEnv: HUB_STATE_BUCKET
  - name: hubStackName
    fromEnv: HUB_STACK_NAME

  - name: component.gke
    parameters:
    - name: name
      value: ${hubStackName}
    - name: zone
      fromEnv: GOOGLE_ZONE
    - name: region
      fromEnv: GOOGLE_REGION      
    - name: nodeCount
      default: 1
      brief: GKE cluster worker nodes count
      fromEnv: GKE_CLUSTER_NODE_COUNT
    - name: machineType
      default: e2-standard-4
      brief: GKE cluster worker nodes machine type
      fromEnv: GKE_CLUSTER_MACHINE_TYPE
    - name: version
      default: 1.21
      brief: Version of Kubernetes API
      fromEnv: GKE_KUBERNETES_VERSION
    - name: imageType
      default: ubuntu
      brief: | 
        Select GKE image type
        See more: https://cloud.google.com/kubernetes-engine/docs/concepts/node-images#available_node_images
      fromEnv: GKE_IMAGE_TYPE
    - name: addons
      value: |
        NetworkPolicy
        NodeLocalDNS
        ConfigConnector

  - name: component.gkeNodePool
    parameters:
    - name: name
      value: cpu-nodes
    - name: clusterName
      value: ${component.gke.name}
    - name: zone
      value: ${component.gke.zone}
    - name: nodeCount
      default: 3
      fromEnv: GKE_NODE_POOL_COUNT
      brief: GKE worker node pool size
    - name: machineType
      value: n1-standard-2
      fromEnv: GKE_NODE_POOL_MACHINE_TYPE
      brief: GKE worker node machine size
    - name: imageType
      default: ubuntu
      brief: | 
        Select GKE image type
        See more: https://cloud.google.com/kubernetes-engine/docs/concepts/node-images#available_node_images
      fromEnv: GKE_IMAGE_TYPE